//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn money with your pool.
        /// </summary>
        internal static string homeDescrizione10 {
            get {
                return ResourceManager.GetString("homeDescrizione10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimmy helps you find small groups of swimmers, friends or families interested in spending some time relaxing in your little paradise..
        /// </summary>
        internal static string homeDescrizione11 {
            get {
                return ResourceManager.GetString("homeDescrizione11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose when to hold the new swimmers!.
        /// </summary>
        internal static string homeDescrizione20 {
            get {
                return ResourceManager.GetString("homeDescrizione20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to Swimmy&apos;s afenda, the swimmers can book only the days you decide to make your swimmingpool available... and after, you choose whether to accept the proposals you receive!.
        /// </summary>
        internal static string homeDescrizione21 {
            get {
                return ResourceManager.GetString("homeDescrizione21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where can you lose yourself?.
        /// </summary>
        internal static string homeDescrizione30 {
            get {
                return ResourceManager.GetString("homeDescrizione30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash! Join this new experience ... Swimmy brings you into the world of #HomeSwimmingPool! Prepare flip flops and towel, what are you waiting?.
        /// </summary>
        internal static string homeDescrizione31 {
            get {
                return ResourceManager.GetString("homeDescrizione31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in touch!.
        /// </summary>
        internal static string homeSottotitolo1 {
            get {
                return ResourceManager.GetString("homeSottotitolo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to be informed when the service will be operating and to be among the first to take advantage of our platform!.
        /// </summary>
        internal static string homeSottotitolo2 {
            get {
                return ResourceManager.GetString("homeSottotitolo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon!.
        /// </summary>
        internal static string homeTitolo {
            get {
                return ResourceManager.GetString("homeTitolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string linguaInglese {
            get {
                return ResourceManager.GetString("linguaInglese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string linguaItaliana {
            get {
                return ResourceManager.GetString("linguaItaliana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string mnuAccedi {
            get {
                return ResourceManager.GetString("mnuAccedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string mnuCerca {
            get {
                return ResourceManager.GetString("mnuCerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string mnuLingua {
            get {
                return ResourceManager.GetString("mnuLingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        internal static string mnuRegistrati {
            get {
                return ResourceManager.GetString("mnuRegistrati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a swimmingpool on Swimmy.
        /// </summary>
        internal static string sottotitoloHome {
            get {
                return ResourceManager.GetString("sottotitoloHome", resourceCulture);
            }
        }
    }
}
